# Generated by Django 3.2.13 on 2022-04-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tanulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azon', models.CharField(max_length=11)),
                ('nev', models.CharField(max_length=25)),
                ('pont', models.FloatField()),
                ('A_eredmeny', models.BooleanField()),
                ('B_eredmeny', models.BooleanField()),
                ('C_eredmeny', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Tanulo',
                'verbose_name_plural': 'Tanulok',
            },
        ),
    ]
